jobs:
  include:
    - stage: test
      language: python
      name: "Test CLI"
      python:
        - "3.4"
      before_install:
        - cd cli
      install:
        - pip install -r requirements.txt -r test-requirements.txt
      script:
        - export PYTHONPATH='.'
        - python -m unittest discover

    - stage: test
      language: python
      name: "Test backend"
      python:
        - "3.4"
      before_install:
        - cd containers/backend
      install:
        - pip install -r requirements.txt
      script:
        - python manage.py test

    - stage: test
      language: node_js
      name: "Test JavaScript packages"
      node_js:
        - "lts/*"
      addons:
        chrome: stable
      cache:
        yarn: true
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH
      install:
        - yarn install
      script:
        - yarn test

    - stage: test
      language: generic
      name: "Test containers"
      services:
        - docker
      before_script:
        - cd containers
      script:
        - ./test.sh

    - stage: deploy
      name: "Deploy containers"
      language: generic
      dist: xenial
      sudo: required
      before_script:
        - sudo add-apt-repository -y ppa:projectatomic/ppa
        - sudo apt-get update -y
        - sudo apt-get install -y podman
        - sudo mkdir -p /etc/containers
        - sudo curl https://raw.githubusercontent.com/projectatomic/registries/master/registries.fedora -o /etc/containers/registries.conf
        - cd containers
      script:
        - ./deploy.sh
