matrix:
  include:
    - language: python
      python:
        - "3.4"
      before_install:
        - cd cli
      install:
        - pip install -r requirements.txt -r test-requirements.txt
      script:
        - python -m unittest discover

    - language: python
      python:
        - "3.4"
      before_install:
        - cd containers/backend
      install:
        - pip install -r requirements.txt
      script:
        - python manage.py test

    - language: generic
      services:
        - docker
      before_script:
        - cd containers
      script:
        - ./test.sh

    - language: node_js
      node_js:
        - "lts/*"
      cache: yarn
      before_install:
        - yarn global add lerna
      install:
        - yarn install
        - lerna bootstrap
      script:
        - yarn test
        - yarn build
