matrix:
  include:
    - language: python
      python:
        - "3.4"
        - "3.7"
      before_script:
        - cd cli
      install:
        - pip install -r requirements.txt -r test-requirements.txt
      script:
        - python -m unittest discover