version: "3"

services:
  db:
    image: postgres:9.5
    volumes:
      - postgresql:/var/lib/postgresql/data
  backend:
    build: ./backend
    expose:
      - '8000'
    links:
      - db
    environment:
      - DATABASE_ENGINE
      - DATABASE_HOST
      - DATABASE_NAME
      - DATABASE_PASSWORD
      - DATABASE_PORT
      - DATABASE_USER
      - DEBUG
      - SECRET_KEY
  webserver:
    build: ./webserver
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./webserver/ssl:/app/ssl
    environment:
      - FQDN

volumes:
  postgresql: