name: deploy-lesspass-pure-package

on:
  push:
    paths:
      - "packages/lesspass-pure/dist/**"

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: test lesspass-pure package
        run: |
          yarn install
          yarn workspace lesspass-pure run test

  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: git hash
        run: |
          git rev-parse HEAD
      - name: deploy lesspass-pure package
        run: |
          cd packages
          ./deploy lesspass-pure
        continue-on-error: true
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
