name: lesspass-web-extension-publish
on:
  push:
    paths:
      - "packages/lesspass-web-extension/**"
jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - run: yarn workspace lesspass-crypto build
      - run: yarn workspace lesspass-pure build
      - run: yarn workspace lesspass-web-extension build
      - run: yarn workspace lesspass-web-extension release
        continue-on-error: true
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
