name: lesspass-pure-publish
on:
  workflow_run:
    workflows: ["lesspass-pure-test"]
    branches: [main]
    types:
      - completed
jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - run: yarn workspace lesspass-crypto run build
      - run: yarn workspace lesspass-pure run build
      - run: |
          cd packages/lesspass-pure
          yarn publish --non-interactive
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
