name: ci

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: test javascript packages
      run: |
        yarn install
        yarn test
